### PR TITLE
delete obsolete ComposeComposableModifier lint check

### PR DESCRIPTION
**Pull request by svenjacobs**
This rule is deprecated as composable Modifier factories are now [officially permitted](https://developer.android.com/develop/ui/compose/custom-modifiers#create_a_custom_modifier_using_a_composable_modifier_factory).

Solves #369

### CODE REVIEW

**Comment by svenjacobs** [comment]
I signed the CLA but nothing is happening 😢

**Comment by svenjacobs** [comment]
@salesforce-cla help

**Comment by svenjacobs** [comment]
> I signed the CLA but nothing is happening 😢

@ZacSweers Can you help, please?

**Comment by ZacSweers** [comment]
am I missing something? 
image

**Comment by svenjacobs** [comment]
> am I missing something? 
> image
> 
> 

Huh, I'm pretty sure I still saw the `cla:missing` tag when I wrote the comment. Weird.

**Review by ZacSweers — APPROVED** [review]
Thanks!

**Pull request merged**
