### PR TITLE
Normalize lint option loading to match with individual issues

### PR DESCRIPTION
**Pull request by seve-andre**
Since v1.3.1, `ComposeCompositionLocalUsageDetector` couldn't fetch the `allowed-composition-locals` list correctly, as mentioned in issue #267. 

After carefully reading the Android Lint API Guide, I found [this](https://googlesamples.github.io/android-custom-lint-rules/api-guide.html#options/supportinglint4.2,7.0and7.1). 

> If your lint check still needs to work with older versions of lint, you can bypass the option registration, and just read option values directly from the configuration. 

The correct way to read the value of the Option, is the following.
```kotlin
 val option: String? = configuration.getOption(ISSUE, OPTION_NAME)
```

### CODE REVIEW

**Review by ZacSweers — COMMENTED** [review]
Should we be fixing all our other options to do this too?

**Comment by seve-andre** [comment]
I think so, but unfortunately, this part lacks sufficient documentation.

**Comment by ZacSweers** [comment]
Sorry finally circling back here. Reading the docs further, this seems to be just limited to supporting older lint versions. We only support the latest stable. With that said, is this still relevant? From what I gather in the docs linked, the actual change we should be making is to use `getValue(context)` instead of `getValue(configuration)`.

**Comment by ZacSweers** [comment]
Hmm, it does seem like maybe this lint doc is ambiguous. Going to update this to use this for backporting and incorporate the new findConfiguration behavior, and separately file an issue asking for clarity

**Review by ZacSweers — APPROVED** [review]

**Pull request merged**
